name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  page_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        sudo apt update
        sudo apt install -y nodejs npm
        sudo npm install -g yarn
        cd ./matrix-js-sdk
        yarn link
        yarn install
        cd ..
        cd ./matrix-react-sdk
        yarn link
        yarn link matrix-js-sdk
        yarn install
        cd ..
        cd ./element-web
        yarn link matrix-js-sdk
        yarn link matrix-react-sdk
        yarn install
        yarn build
        cd ..
        cp ./assets/config.json ./element-web/webapp/
        cp ./assets/logo.svg ./element-web/webapp/themes/element/img/logos/element-logo.svg

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: element-web/webapp
